from enum import Enum


class Environment(str, Enum):
    SANDBOX = 'SANDBOX',
    STAGING = 'STAGING',
    PRODUCTION = 'PRODUCTION'


class Product(str, Enum):
    IDENTITY = 'IDENTITY'
    IDENTITY_AUDIENCE = 'IDENTITY.AUDIENCE'
    ENGAGEMENT = 'ENGAGEMENT'
    ENGAGEMENT_AUDIENCE = 'ENGAGEMENT.AUDIENCE'
    INCOME = 'INCOME'
    PUBLISH_CONTENT = 'PUBLISH.CONTENT'
    ACTIVITY = 'ACTIVITY'
    CREATOR_SEARCH = 'CREATOR.SEARCH'
    PUBLIC_CONTENT_SEARCH = 'PUBLIC.CONTENT.SEARCH'


class HTTPMethod(str, Enum):
    GET = 'GET'
    POST = 'POST'
    PUT = 'PUT'
    PATCH = 'PATCH'
    DELETE = 'DELETE'
    OPTIONS = 'OPTIONS'
    HEAD = 'HEAD'


class PlatformCategory(str, Enum):
    COMMERCE = 'COMMERCE'
    SOCIAL = 'SOCIAL'


class WebhookEvent(str, Enum):
    ACCOUNTS_CONNECTED = 'ACCOUNTS.CONNECTED'
    ACCOUNTS_DISCONNECTED = 'ACCOUNTS.DISCONNECTED'
    PROFILES_ADDED = 'PROFILES.ADDED'
    PROFILES_UPDATED = 'PROFILES.UPDATED'
    PROFILES_AUDIENCE_ADDED = 'PROFILES_AUDIENCE.ADDED'
    PROFILES_AUDIENCE_UPDATED = 'PROFILES_AUDIENCE.UPDATED'
    CONTENTS_ADDED = 'CONTENTS.ADDED'
    CONTENTS_UPDATED = 'CONTENTS.UPDATED'
    CONTENTS_COMMENTS_ADDED = 'CONTENTS_COMMENTS.ADDED'
    CONTENTS_COMMENTS_UPDATED = 'CONTENTS_COMMENTS.UPDATED'
    CONTENT_GROUPS_ADDED = 'CONTENT-GROUPS.ADDED'
    CONTENT_GROUPS_UPDATED = 'CONTENT-GROUPS.UPDATED'
    TRANSACTIONS_ADDED = 'TRANSACTIONS.ADDED'
    TRANSACTIONS_UPDATED = 'TRANSACTIONS.UPDATED'
    PAYOUTS_ADDED = 'PAYOUTS.ADDED'
    PAYOUTS_UPDATED = 'PAYOUTS.UPDATED'
    BALANCES_ADDED = 'BALANCES.ADDED'
    BALANCES_UPDATED = 'BALANCES.UPDATED'
    ACTIVITY_ARTISTS_ADDED = 'ACTIVITY-ARTISTS.ADDED'
    ACTIVITY_ARTISTS_UPDATED = 'ACTIVITY-ARTISTS.UPDATED'
    ACTIVITY_CONTENTS_ADDED = 'ACTIVITY-CONTENTS.ADDED'
    ACTIVITY_CONTENTS_UPDATED = 'ACTIVITY-CONTENTS.UPDATED'
    CONTENTS_PUBLISH_SUCCESS = 'CONTENTS.PUBLISH_SUCCESS'
    CONTENTS_PUBLISH_FAILURE = 'CONTENTS.PUBLISH_FAILURE'
    CONTENTS_PUBLISH_READY = 'CONTENTS.PUBLISH_READY'
    SESSION_EXPIRED = 'SESSION.EXPIRED'


product_webhook_event_mapping = {
    Product.IDENTITY: {WebhookEvent.PROFILES_ADDED, WebhookEvent.PROFILES_UPDATED},
    Product.IDENTITY_AUDIENCE: {WebhookEvent.PROFILES_AUDIENCE_ADDED, WebhookEvent.PROFILES_AUDIENCE_UPDATED},
    Product.ENGAGEMENT: {WebhookEvent.CONTENTS_ADDED, WebhookEvent.CONTENTS_UPDATED,
                         WebhookEvent.CONTENT_GROUPS_ADDED, WebhookEvent.CONTENT_GROUPS_UPDATED, },
    Product.ENGAGEMENT_AUDIENCE: {WebhookEvent.CONTENTS_COMMENTS_ADDED, WebhookEvent.CONTENTS_COMMENTS_UPDATED},
    Product.INCOME: {WebhookEvent.TRANSACTIONS_ADDED, WebhookEvent.TRANSACTIONS_UPDATED,
                     WebhookEvent.PAYOUTS_ADDED, WebhookEvent.PAYOUTS_UPDATED,
                     WebhookEvent.BALANCES_ADDED, WebhookEvent.BALANCES_UPDATED},
    Product.PUBLISH_CONTENT: {WebhookEvent.CONTENTS_PUBLISH_SUCCESS, WebhookEvent.CONTENTS_PUBLISH_FAILURE,
                              WebhookEvent.CONTENTS_PUBLISH_READY},
    Product.ACTIVITY: {WebhookEvent.ACTIVITY_ARTISTS_ADDED, WebhookEvent.ACTIVITY_ARTISTS_UPDATED,
                       WebhookEvent.ACTIVITY_CONTENTS_ADDED, WebhookEvent.ACTIVITY_CONTENTS_UPDATED}
}
